name: Install ArgoCD and Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy ArgoCD & Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Install Argo CD
      run: |
        kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

        # Wait for Argo CD server to be ready
        kubectl wait deployment argocd-server -n argocd --for=condition=Available=True --timeout=180s

    - name: Create Argo CD Application
      run: |
        kubectl apply -f - <<EOF
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: my-app
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: https://github.com/YOUR_GITHUB_USER/YOUR_REPO
            targetRevision: HEAD
            path: path/to/manifests
          destination:
            server: https://kubernetes.default.svc
            namespace: default
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
        EOF

