name: CI - Terraform and ACR Integration

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: .
  TF_VAR_IMAGE_TAG: ${{ github.run_id }}

jobs:
  validate-plan-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ${{ env.TF_WORKING_DIR }}
        
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Run tfsec (security scan)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Run Checkov (security scan)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Show Terraform Plan Output
        run: terraform show tfplan -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/chatui:${{ env.TF_VAR_IMAGE_TAG }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/chatui:${{ env.TF_VAR_IMAGE_TAG }}
