name: TF Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: .
  TF_VAR_IMAGE_TAG: ${{ github.run_id }}

jobs:
  validate-plan-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy (parallel & quick)
        working-directory: ./terraform
        run: terraform destroy -auto-approve -parallelism=50

