name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  plan-destroy:
    name: Terraform Plan - Destroy
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan.destroy

      - name: Upload Destroy Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-destroy
          path: tfplan.destroy

  apply-destroy:
    name: Terraform Apply - Destroy
    needs: plan-destroy
    runs-on: ubuntu-latest
    environment:
      name: production  # GitHub Environments required for manual approval
      url: https://portal.azure.com  # Optional link for reviewers

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Download Destroy Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-destroy
          path: .

      - name: Terraform Apply (Destroy)
        run: terraform apply -auto-approve tfplan.destroy
